name: Build and Run Fastfetch

on:
  push:
    branches:
      - main

jobs:
  build-and-log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git cmake gcc libpci-dev libdrm-dev

      - name: Clone and build fastfetch
        run: |
          git clone https://github.com/fastfetch-cli/fastfetch
          cd fastfetch
          mkdir build && cd build
          cmake ..
          make -j$(nproc)
          ./fastfetch > ../../fastfetch_log.txt

      - name: Commit output
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add fastfetch_log.txt
          git commit -m "Add fastfetch log [skip ci]" || echo "No changes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
